export PIP_REQUIRE_VIRTUALENV=false
export PATH=/usr/local/opt/python/libexec/bin:/usr/local/opt/python/libexec/bin:/usr/local/share/python:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Wireshark.app/Contents/MacOS
export SPARK_HOME=/Users/peter.may@ibm.com/spark-2.1.0-bin-hadoop2.6
export SCALA_HOME=/usr/local/Cellar/scala@2.11/2.11.12
export PIXIEDUST_TEST_INPUT=/Users/peter.may@ibm.com/Documents/Github/pixiedust/tests
export PROMPT_COMMAND='echo -ne "\033]0;$PWD\007"'
export PATH=/usr/local/opt/node@8/bin:/Users/peter.may@ibm.com/anaconda2/bin:/usr/local/opt/python/libexec/bin:/usr/local/opt/python/libexec/bin:/usr/local/share/python:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/peter.may@ibm.com/maven/apache-maven-3.5.4/bin
export PATH=/usr/local/opt/node@8/bin:/Users/peter.may@ibm.com/anaconda2/bin:/usr/local/opt/node@8/bin:/Users/peter.may@ibm.com/anaconda2/bin:/usr/local/opt/python/libexec/bin:/usr/local/opt/python/libexec/bin:/usr/local/share/python:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/peter.may@ibm.com/maven/apache-maven-3.5.4/bin
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
